import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './normalize.css';
import './reset.css';
import './global.css';
import styles from '@/app/(beforeLogin)/_component/Main.module.css';
import { MSWComponent } from './_components/MSWComponent';
import AuthSession from './_components/AuthSession';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWComponent />
        <AuthSession>
          <div className={styles.container}>{children}</div>
        </AuthSession>
      </body>
    </html>
  );
}
